### ISSUE TITLE
Support Dropping Rows

### ISSUE THREAD

**Issue by zacharylawrence** [xguse/table_enforcer#1]
Some data sets have invalid rows that should be dropped (eg. test rows, rows with no data, etc.). Does table_enforcer have support for "recoding" that alters the length of rows?

**Comment by xguse** [comment]
I have not worked on this repo in a while so I can't quite remember exactly but you could easily add that to the end of your loading function after the recoding of the columns is done. The problem with trying to do that when you are recoding a column is that you need to know everything about all rows for that to work. Thats why its better suited to after your table's columns are ship-shape and you have put the table back together.

Then you can do a `dropna` type function on axis=0 with how='all' or something.
